---
deployment:
  tasks:
    - export REPO_PATH=/home/omansoun/repositories/web/
    - export DEPLOY_PATH=/home/omansoun/public_html/
    - echo "Deploying application from $REPO_PATH to $DEPLOY_PATH"
    - /bin/cp -r $REPO_PATH/* $DEPLOY_PATH
    - echo "Deployment completed successfully!"